## Load and preprocess Iris Data

In [23]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import pickle

#Load and preprocess the Iris dataset
data = load_iris()
X = data.data
y = data.target

In [24]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
y


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:

#Split the dataset into training and testing sets
#USing first 50% for training and remaining 50% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

#Standardize the features
#Imortant to scale the features so that every feature get equal 
#chance of appearing in classification.

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



## Create ANN Architecture

In [27]:
#Architecture of the neural network
#Topology 5-2-3
input_size = X_train.shape[1]
hidden_size = 2
output_size = 3
learning_rate = 0.01
epochs = 10000

#Initialize weights and biase for the network
np.random.seed(0)
weights_input_hidden = np.random.randn(input_size, hidden_size)
bias_hidden = np.zeros(hidden_size)
weights_hidden_output = np.random.randn(hidden_size, output_size)
bias_output = np.zeros(output_size)

# softmax function for the output layer
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)



## Training ANN 

In [28]:
#Train the neural network
for epoch in range(epochs):
    # Forward pass with 3 layers. 
    hidden_input = np.dot(X_train, weights_input_hidden) + bias_hidden
    # usign ReLU activation function in hidden layer (ReLU(x) = max(0, x))
    hidden_output = np.maximum(0, hidden_input)  
    output_input = np.dot(hidden_output, weights_hidden_output) + bias_output
    predicted_probabilities = softmax(output_input)

    # Calculate the loss
    num_samples = X_train.shape[0]
    loss = -np.log(predicted_probabilities[range(num_samples), y_train]).mean()

    # Backpropagation
    d_output = predicted_probabilities
    d_output[range(num_samples), y_train] -= 1
    d_output /= num_samples

    d_hidden = np.dot(d_output, weights_hidden_output.T)
    d_hidden[hidden_input <= 0] = 0

    d_weights_hidden_output = np.dot(hidden_output.T, d_output)
    d_bias_output = np.sum(d_output, axis=0)
    d_weights_input_hidden = np.dot(X_train.T, d_hidden)
    d_bias_hidden = np.sum(d_hidden, axis=0)

    # Update the weights and biases
    weights_input_hidden -= learning_rate * d_weights_input_hidden
    bias_hidden -= learning_rate * d_bias_hidden
    weights_hidden_output -= learning_rate * d_weights_hidden_output
    bias_output -= learning_rate * d_bias_output

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss {loss:.4f}")


Epoch 0: Loss 1.0063
Epoch 100: Loss 0.5732
Epoch 200: Loss 0.5234
Epoch 300: Loss 0.4871
Epoch 400: Loss 0.4593
Epoch 500: Loss 0.4372
Epoch 600: Loss 0.4194
Epoch 700: Loss 0.4046
Epoch 800: Loss 0.3918
Epoch 900: Loss 0.3810
Epoch 1000: Loss 0.3715
Epoch 1100: Loss 0.3633
Epoch 1200: Loss 0.3559
Epoch 1300: Loss 0.3493
Epoch 1400: Loss 0.3433
Epoch 1500: Loss 0.3378
Epoch 1600: Loss 0.3327
Epoch 1700: Loss 0.3279
Epoch 1800: Loss 0.3234
Epoch 1900: Loss 0.3191
Epoch 2000: Loss 0.3150
Epoch 2100: Loss 0.3110
Epoch 2200: Loss 0.3073
Epoch 2300: Loss 0.3036
Epoch 2400: Loss 0.3000
Epoch 2500: Loss 0.2965
Epoch 2600: Loss 0.2931
Epoch 2700: Loss 0.2898
Epoch 2800: Loss 0.2866
Epoch 2900: Loss 0.2834
Epoch 3000: Loss 0.2804
Epoch 3100: Loss 0.2773
Epoch 3200: Loss 0.2744
Epoch 3300: Loss 0.2715
Epoch 3400: Loss 0.2671
Epoch 3500: Loss 0.2621
Epoch 3600: Loss 0.2571
Epoch 3700: Loss 0.2523
Epoch 3800: Loss 0.2476
Epoch 3900: Loss 0.2431
Epoch 4000: Loss 0.2386
Epoch 4100: Loss 0.2343
Epoc

Epoch 0: Loss 0.0850
Epoch 100: Loss 0.0842
Epoch 200: Loss 0.0834
Epoch 300: Loss 0.0827
Epoch 400: Loss 0.0820
Epoch 500: Loss 0.0813
Epoch 600: Loss 0.0806
Epoch 700: Loss 0.0799
Epoch 800: Loss 0.0792
Epoch 900: Loss 0.0786
Epoch 1000: Loss 0.0779
Epoch 1100: Loss 0.0773
Epoch 1200: Loss 0.0767
Epoch 1300: Loss 0.0761
Epoch 1400: Loss 0.0756
Epoch 1500: Loss 0.0750
Epoch 1600: Loss 0.0745
Epoch 1700: Loss 0.0739
Epoch 1800: Loss 0.0734
Epoch 1900: Loss 0.0729
Epoch 2000: Loss 0.0725
Epoch 2100: Loss 0.0720
Epoch 2200: Loss 0.0715
Epoch 2300: Loss 0.0711
Epoch 2400: Loss 0.0706
Epoch 2500: Loss 0.0702
Epoch 2600: Loss 0.0697
Epoch 2700: Loss 0.0693
Epoch 2800: Loss 0.0689
Epoch 2900: Loss 0.0685
Epoch 3000: Loss 0.0681
Epoch 3100: Loss 0.0677
Epoch 3200: Loss 0.0673
Epoch 3300: Loss 0.0670
Epoch 3400: Loss 0.0666
Epoch 3500: Loss 0.0662
Epoch 3600: Loss 0.0659
Epoch 3700: Loss 0.0655
Epoch 3800: Loss 0.0652
Epoch 3900: Loss 0.0649
Epoch 4000: Loss 0.0645
Epoch 4100: Loss 0.0642
Epoc

## Validation

In [29]:
# Evaluation on the test data
hidden_input_test = np.dot(X_test, weights_input_hidden) + bias_hidden
hidden_output_test = np.maximum(0, hidden_input_test)
output_input_test = np.dot(hidden_output_test, weights_hidden_output) + bias_output
predicted_probabilities_test = softmax(output_input_test)
predicted_labels_test = np.argmax(predicted_probabilities_test, axis=1)

accuracy = (predicted_labels_test == y_test).mean()
print(f"Test accuracy: {accuracy:.2f}")

Test accuracy: 0.99


In [30]:
predicted_labels_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1], dtype=int64)

In [31]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0,
       1, 2, 0, 1, 2, 0, 2, 2, 1])

In [32]:
model = {
    "weights_input_hidden": weights_input_hidden,
    "bias_hidden": bias_hidden,
    "weights_hidden_output": weights_hidden_output,
    "bias_output": bias_output,
}

In [33]:
with open("iris_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [40]:
import numpy as np
import tkinter as tk
from tkinter import messagebox

#Load ANN model
with open("iris_model.pkl", "rb") as f:
    model = pickle.load(f)

#Class labels for Iris dataset
class_labels = ["Iris Setosa", "Iris Versicolor", "Iris Verginica"]

# Function to make predictions
def predict():
    try:
        # Get user inputs
        feature1 = float(entry_feature1.get())
        feature2 = float(entry_feature2.get())
        feature3 = float(entry_feature3.get())
        feature4 = float(entry_feature4.get())

        input_features = np.array([feature1, feature2, feature3, feature4]).reshape(1, -1)

        weights_input_hidden = model["weights_input_hidden"]
        bias_hidden = model["bias_hidden"]
        weights_hidden_output = model["weights_hidden_output"]
        bias_output = model["bias_output"]

        hidden_input = np.dot(input_features, weights_input_hidden) + bias_hidden
        hidden_output = np.maximum(0, hidden_input)
        output_input = np.dot(hidden_output, weights_hidden_output) + bias_output
        predicted_probabilities = softmax(output_input)

        predicted_class_index = np.argmax(predicted_probabilities)
        predicted_class_label = class_labels[predicted_class_index]

        result_label.config(text=f'Predicted Class: {predicted_class_label}')

    except Exception as e:
        messagebox.showerror("Error", str(e))

# Create the tkinter window
window = tk.Tk()
window.title("ANN Prediction GUI")
window.geometry("400x300")
entry_feature1 = tk.Entry(window)
entry_feature2 = tk.Entry(window)
entry_feature3 = tk.Entry(window)
entry_feature4 = tk.Entry(window)

entry_feature1.grid(row=0, column=1)
entry_feature2.grid(row=1, column=1)
entry_feature3.grid(row=2, column=1)
entry_feature4.grid(row=3, column=1)

label_feature1 = tk.Label(window, text="Sepal Length:")
label_feature2 = tk.Label(window, text="Sepal Width:")
label_feature3 = tk.Label(window, text="Petal Length:")
label_feature4 = tk.Label(window, text="Petal Width:")

label_feature1.grid(row=0, column=0)
label_feature2.grid(row=1, column=0)
label_feature3.grid(row=2, column=0)
label_feature4.grid(row=3, column=0)

predict_button = tk.Button(window, text="Predict", command=predict)
predict_button.grid(row=4, columnspan=2)

result_label = tk.Label(window, text="")
result_label.grid(row=5, columnspan=2)

window.mainloop()
